language: php

dist: trusty
sudo: false

cache:
    directories:
        - $HOME/.composer/cache/files
        - .phpunit

matrix:
    include:
        - php: 7.2
        - php: 7.3
        - php: 7.4
          env: composer_extra="--prefer-lowest --prefer-stable"
    fast_finish: true

install:
    - composer $composer_extra update

script:
    - ./vendor/bin/simple-phpunit
